Accounts/urls.py
from django.urls import path
from Accounts import views
from django.conf import settings
from django.conf.urls.static import static

app_name ="Accounts" #custom url
urlpatterns = [
	path('register/', views.register_user, name='register_user'),
	path('login/', views.login_user, name='login_user'),
	path('logout/', views.logout_user, name='logout_user')
]

urlpatterns +=  static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)


urlpatterns +=  static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

Elibrary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Accounts.urls')),
    path('', include('ReadBook.urls'))
]

ReadBook/urls.py
from django.urls import path, include
from .import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "ReadBook" #custom url which is very important

urlpatterns = [
	path('', views.loadBook, name='premiumbook'),
	path('addbook/',views.addBook, name='addbook'),
	path('description/<int:bid>/', views.bookDescription, name='description'),
	path('delete/<int:bid>/', views.deleteBook, name='deletebook')
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Accounts/models.py
from django.db import models

# Create your models here.

ReadBook/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserInfo(models.Model):
	users = models.OneToOneField(User, on_delete = models.CASCADE)

	#these are extended models features
	user_type = models.CharField(max_length = 6)


	#dunder method or magic method or special method
	def __str__(self):
		return self.users.username



class Book(models.Model):
	book_name = models.CharField(max_length = 60)
	uploaded_by = models.ForeignKey(UserInfo, on_delete= models.CASCADE)
	book_price = models.IntegerField(default=0)
	book_type = models.CharField(max_length = 10)
	book_cover = models.ImageField(upload_to='book_images/')
	book_description = models.TextField()
	book_category = models.CharField(max_length = 60)
	book_file = models.FileField(upload_to='book/')
	upload_date = models.DateTimeField(auto_now_add = True)


	def __str__(self):
		return str(self.book_name)

Accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.http import HttpResponse
from ReadBook.models import UserInfo
from django.contrib.auth import authenticate, login, logout
# Create your views here.
def register_user(request):
	if not request.user.is_authenticated:
		if request.method == "POST":
			first_name = request.POST['first_name']
			last_name = request.POST['last_name']
			username = request.POST['username']
			email = request.POST['email']
			user_type = request.POST['user_type']
			password1 = request.POST['password1']
			password2 = request.POST['password2']

			if password1 == password2:
				if User.objects.filter(username = username).exists():
					messages.info(request,'Username is taken. Choose Another')
					return redirect('Accounts:register_user')

				elif User.objects.filter(email = email).exists():
					messages.info(request,"Email is taken. Take another email")
					return redirect('Accounts:register_user')

				else:
					user = User.objects.create_user(username = username, password = password1,first_name = first_name, 
						last_name = last_name, email = email)
					user.save()
					UserInfo.objects.create(id = user.id, user_type = user_type, 
						users_id = user.id)
					return redirect('Accounts:login_user')
				#pretty Jharna123
				#muksam ethicalhacker
			else:
				messages.info(request,'Password does not matched')
				return redirect('Accounts:register_user')
	return render(request,'Accounts/register.html')


def login_user(request):
	if not request.user.is_authenticated:
		if request.method == "POST":
			username = request.POST['username']
			password = request.POST['password']

			user = auth.authenticate(username = username, password = password)
			if user is not None:
				auth.login(request, user)
				return redirect('/')
			else:
				messages.info(request,f'Invalid Credential')
				return redirect("Accounts:login_user")#<app_name>:<url> custom url
		else:
			return render(request,'Accounts/login.html')
	else:
		return HttpResponse("You are not permitted to view this page")

def logout_user(request):
	auth.logout(request)
	return redirect('Accounts:login_user')

ReadBook/views.py
from django.shortcuts import render, redirect
from .models import Book
from .decorators import author_only
from django.contrib.auth.decorators import login_required
# Create your views here.
def loadBook(request):
	books = Book.objects.all()
	context = {'books':books}
	return render(request,'Readbook/book.html',context)

@login_required(login_url='/login/')
@author_only
def addBook(request):
	name = ''
	price = ''
	btype = ''
	cover = ''
	pdf = ''
	description =''
	category = ''
	userid = ''
	if request.method == "POST":

		try:
			name = request.POST['name'].strip() #removes white space
			btype = request.POST['btype'].strip() #remove white space
			description = request.POST['description']
			category = request.POST['category']
			cover = request.FILES.get('image', None)
			pdf = request.FILES.get('file')
			userid = request.user.id


			if btype != 'Free':
				price = int(request.POST['price'])
			else:
				price = 0

			Book.objects.create(book_name = name, book_price = price, book_type = btype,
				book_category = category, book_cover = cover, book_description = description,
				book_file = pdf, uploaded_by_id = userid)
			return redirect("Readbook:premiumbook")

		except Exception as e:
			print("Error:"+str(e))


	return render(request,'Readbook/AddBook.html', context ={
			'bookname':name,
			'bookprice':price,
			'category':category,
			'description':description

		})


def bookDescription(request, bid):
	book = None
	owner = False
	loggedin = True if request.user.is_authenticated else False

	if Book.objects.filter(id = bid).exists():
		try:
			book = Book.objects.get(id=bid)
			if loggedin:
				owner = True if Book.objects.get(pk=bid).uploaded_by_id == request.user.id else False
		except Exception as e:
			print(str(e))

	else:
		return redirect('ReadBook:premiumbook')

	return render(request,'Readbook/BookDescription.html',context={
			'book' : book,
			'loggedin' : loggedin,
			'owner' : owner

		})

@login_required(login_url='/login/')
@author_only
def deleteBook(request, bid):
	book = None
	if Book.objects.filter(id = bid).exists():
		book = Book.objects.get(id = bid)
		book.delete()
	return redirect('ReadBook:premiumbook')

templates/Accounts/login.html
{% extends 'Base/Header.html' %}
{% block content %}
{% if messages %}
	{% for message in messages %}
		<div {% if message.tags %} class="{{ message.tags }} alert-danger" {% endif %} id="alert">
			{{ message}}
		<i class="material-icons" style="color:black; float:right; cursor: pointer;" id="closealert">
			close
		</i>
		</div>
	{% endfor %}

{% endif %}
<form method ="POST">
	{% csrf_token %}
	<input type="text" name="username" placeholder="Enter your Username"><br>
	<input type="password" name="password" placeholder="Enter your Password"><br><br>

	<input type="submit" name="Login" class="btn">
</form>

{% endblock content %}

templates/Accounts/register.html
{% extends 'Base/Header.html' %}
{% block content %}
<form method = "POST">
	{% csrf_token %}
	<input type="text" name="first_name" placeholder="First Name"><br>
	<input type="text" name="last_name" placeholder="Last Name"><br>

	<input type="text" name="username" placeholder="User Name"><br>

	<input type="text" name="email" placeholder="Enter Your Email.."><br>

	<!-- Making choose option for author and reader-->
	<p>Choose author type:</p>
	<div class="input-field col 14">
		<select name="user_type" style="display: block;">
			<option disabled=""> Choose </option>
			<option>Reader</option>
			<option>Author</option>
		</select>
	</div><br>

	<input type="password" name="password1" placeholder="Enter your Password.."><br>

	<input type="password" name="password2"
	placeholder="Enter your password Again.."><br>

	<input type="submit" name="Register" class="btn">
</form>
<h3>Already have an account? <a href="Accounts/login.html">Sign In</a></h3>
{% endblock content %}

templates/Base/Header.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Read Book</title>

    <!-- jquery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Compiled and minified CSS materialized -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
    <!-- CDN for Icon -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    <!-- Compiled and minified JavaScript for materialized -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <!-- individaul css -->


    <!-- individaul Javascript/Jquery -->

  </head>

  <body>
    {% include "./Navbar.html" %}
    <div class="container">
      {% block content %} {% endblock %}
    </div>
  </body>
</html>

templates/Base/Navbar.html
<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content" style="height:0px;">
  
</ul>
<nav>
  <div class="nav-wrapper">
    <a href="/" class="brand-logo" style="margin-left: 60px;">E-Library</a>
    <ul class="right hide-on-med-and-down" style="height: 0px;">
      
      <li>
        <a href=""><i class="material-icons" style="display: inline; vertical-align: bottom;">book</i>My Books</a>
      </li>
      <li>
        <a href="{% url 'ReadBook:addbook' %}"><i class="material-icons" style="display: inline; vertical-align: bottom;">add</i>AddBook</a><br />
      </li>
      
      <li>
        <span style="font-weight: 501;border: 1px solid;padding: 5px;border-radius: 3px;vertical-align: sub;margin: 5px;">
          <i class="material-icons" style="display: inline;vertical-align: bottom;">account_balance_wallet</i> 
        </span>
      </li>

      <li><a href="/admin/" style="font-weight: 501;">Admin</a><br /></li>

      <!-- Dropdown Trigger -->
      <li>
        <a class="dropdown-trigger" href="#!" data-target="dropdown1">
          <span style="font-weight: 501;">
            <i class="material-icons" style="display: inline; vertical-align: bottom;">account_circle</i>
            {{request.user.is_authenticated|yesno:',Login'}}{% firstof request.user.username|title %}
            <i class="material-icons right" style="margin-left: 0px;">arrow_drop_down </i>
          </span>
        </a>
      </li>
    </ul>
  </div>
</nav>
<nav style="width: 500px; margin-top: -65px; margin-left: 380px; margin-bottom: 20px;">
  <div class="nav-wrapper" style="width: 500px; ">
    <form method="GET" action=''>
      <div class="input-field">
        <input id="search" type="search" name="q" placeholder="Search" />
        <label class="label-icon" for="search"><i class="material-icons">search</i></label>
        <i class="material-icons">close</i>
      </div>
    </form>
  </div>
</nav>
<script type="text/javascript">
  $(document).ready(function() {
    $(".dropdown-trigger").dropdown();
  });
</script>

templates/Readbook/AddBook.html
{% extends 'Base/Header.html' %} 
{% load static %}
{% block content %} 

       
       <form method="POST" enctype = "multipart/form-data" style="padding-top: 20px;" id="addbookfor">

        {% csrf_token %}
        <div class="input-field col s12 m6">

            <label for="bookname"> Book Title </label>
            <input type="text" name="name" id="bookname" class="validate" 
            required value="{{bookname}}">

        </div>


         <div class="input-field col s12 m6">

            <label for="category"> Book Category </label>
            <input type="text" name="category" id="category" class="validate" 
            required value="{{category}}">

        </div>


         <div class="col s12 m6">

            <label for="booktype" class="fs15"> Book Type: </label>
            <select name="btype" id="booktype" style="display: block; " required>
              <option value="" disabled selected>Choose your option</option>
              <option value="Premium">Premium</option>
              <option value="Free">Free</option>


        </div>

        <div class="input-field col s12 m6">

            <label for="bookprice"> Book Price </label>
            <input type="Number" name="price" id="bookprice" class="validate" 
            required value="{{bookprice}}">

        </div>


        <div class="col s12 m6">

            <label for="bookcover"> Book Cover: </label>
            <div class="file-field input-field">

              <div class="btn">

                    <span>Upload</span>

                    <input type="file" name="image" accept="image/jpeg" 
                    id="bookcover">
              </div>
              <div class="file-path-wrapper">

                <input type="file-path validate" type="text" 
                placeholder="Upload book cover" id="bookcoverpath">

              </div>
            </div>

        </div>



<!-- book pdf -->
<div class="col s12 m6">

            <label for="bookfile"> Book File: </label>
            <div class="file-field input-field">

              <div class="btn">

                    <span>Upload</span>

                    <input type="file" name="file" accept="application/pdf" 
                    id="bookfile" required>
              </div>
              <div class="file-path-wrapper">

                <input type="file-path validate" type="text" 
                placeholder="Upload book pdf" id="bookfilepath">

              </div>
            </div>

        </div>

        <div class="col s12">
          <label for="bookdescription" class="fs15">Abstract of a book</label>
          <textarea
            name="description"
            id="bookdescription"
            style="height: 8rem; resize: none; border: solid 0.5px 
            #9e9e9e; margin-top: 5px" placeholder="Description" required>{{description}}
          </textarea>


        </div>

        <div>
          <div class="input-field col s12 m6">
          <button type="button" class="btn waves-effect waves-light" style="width: 100%;"
            id="cancel"
            >Cancel</button>
          </div>
        </div>



        <div>
          <div class="input-field col s12 m6">
          <button type="submit" 
          class="btn waves-effect waves-light" style="width: 100%;">Add Book</button>
          </div>
        </div>



       </form>




      </div>
    </div>
  </div>
</div>
<script>
  // for disabling price input filed
  

  //auto add text
  $(document).ready(function() {
    //on load
    if ($("#bookname").val()) {
      $("#add_title").text($("#bookname").val());
    }
    if ($("#category").val()) {
      $("#add_cat_type").text($("#category").val());
    }
    if ($("#bookdescription").val()) {
      $("#add_description").text($("#bookdescription").val());
    }
    //on change
    $("#bookname").change(function() {
      $("#add_title").text($(this).val());
    });
    $("#category").change(function() {
      $("#add_cat_type").text($(this).val());
    });
    $("#booktype").change(function() {
      $("#add_book_type").text(" | " + $("#booktype option:selected").val());
    });
    $("#bookdescription").change(function() {
      $("#add_description").text($(this).val());
    });
  });

  $(document).ready(function() {
    $("#cancel").click(function() {
      $("#addbookform").trigger("reset");
      $("#add_title").text("");
      $("#add_cat_type").text("");
      $("#add_description").text("");
    });
  });

  //to pre load images addded in the field
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function(e) {
        $("#uploadedpic").attr("src", e.target.result);
      };

      reader.readAsDataURL(input.files[0]);
    }
  }
  $("#bookcover").change(function() {
    readURL(this);
  });
</script>
{% endblock %}

templates/Readbook/BookDescription.html
{% extends 'Base/Header.html' %} {% block content %}

    {% if not book.book_price %}
      <!-- free -->
      <a href="" class="btn waves-effect" style="width:100%" target="_blank"><i class="material-icons" style="vertical-align: inherit;"> chrome_reader_mode</i> Free </a>

      <!-- buy -->
      <div style="margin: 10px;">
        <form action="" method="POST">
          {% csrf_token %}
          <button class="btn waves-effect" type="submit" style="width:100%">
            ${{book.book_price}}
          </button>
        </form>
      </div>
      {% elif loggedin %}
      <!-- bought -->
      <div style="margin: 10px;">
        <a href="" class="btn waves-effect" style="width:100%" target="_blank"
          ><i class="material-icons" style="vertical-align: inherit;"> file_download</i> DOWNLOAD</a
        >
      </div>
      {% endif %}
    </div>
    <!-- image section ends -->

    <!-- description section -->
    <div class="col s12 m6 l7">
      <div class="" style="height:0px; min-height: 367px; margin-bottom: 13px; padding: 10px; border-bottom: 1px solid #8a8a8a82; overflow: hidden;">
        <h6 style="margin-top: 5px; font-weight: 501; display: inline-block;">
          Description:
        </h6>
        <i class="material-icons b_description_down">keyboard_arrow_down</i>
        <p style="text-align: justify; margin:5px 0px;">
          &emsp; {{book.book_description}}
        </p>
      </div>
    </div>
    <!-- description section ends -->

          </form>


{% endblock %}

templates/Readbook/book.html
{% extends 'Base/Header.html' %}
{% load static %}
{% block content %}

<div class="row">

{% if not books %}

	<h3 align="center" style="color: #9e9e9e">No Books to display</h3>

{% else %}

{% for book in books %}

	<div class="col s6 m5 14">
		<div class="card">
			<div class="card-image">
				<a href="{% url 'ReadBook:description' book.id %}" style="color: white;">
				<img src="{{book.book_cover.url}}" style="height:290px; border: 1px solid #9e9e9e; padding: 5px"/>
					
				</a>
			</div>
			<div class="card-content" style="overflow:hidden; border-top: 1px solid
			rgba(113, 112, 112, 0.3); padding: 0px" >

			<div style="background: #26a69a; padding: 2px 13px;">
			<a href="" style="color: white;">
					<span class="card-title"> {{book.book_name|title}}</span>

			</a>
			</div>


			</div>

			<div style="margin-left: auto;">
				<a href="" class="btn-waves-effect">

					{{book.book_price|yesno:'$,Free'}} {% firstof book.book_price %}


				</a>

			</div>



	</div>


{% endfor %} {% endif %}


</div>

{% endblock content  %}